# Generated by Django 6.0.2 on 2026-02-09 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('script', 'скрипт'), ('texture', 'текстура'), ('audio', 'аудіо'), ('graphic', 'графіка')], max_length=20)),
                ('fps_impact', models.IntegerField(default=0, help_text='Вплив на FPS')),
                ('file_url', models.URLField(help_text='Посилання на файл у хмарі')),
                ('conflicts_with', models.ManyToManyField(blank=True, to='builds.component')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Створено ШІ')),
                ('performance_score', models.IntegerField(default=0, help_text='Оцінка продуктивності від ШІ')),
                ('min_ram_required', models.IntegerField(default=4)),
                ('tags', models.CharField(help_text='Наприклад: Low-PC, Winter, Realistic', max_length=255)),
                ('source_file', models.FileField(upload_to='build_archives/')),
                ('torrent_file', models.FileField(blank=True, null=True, upload_to='torrents/')),
                ('magnet_link', models.TextField(blank=True, null=True)),
                ('info_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('trackers', models.TextField(default='udp://tracker.openbittorrent.com:80/announce,udp://tracker.opentrackr.org:1337/announce')),
                ('components', models.ManyToManyField(related_name='builds', to='builds.component')),
            ],
        ),
        migrations.CreateModel(
            name='PCSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Мій ПК', help_text='Напр: Домашній ПК або Ноутбук', max_length=100)),
                ('cpu_model', models.CharField(max_length=255, verbose_name='Процесор')),
                ('gpu_model', models.CharField(max_length=255, verbose_name='Відеокарта')),
                ('ram_gb', models.IntegerField(default=0, verbose_name='ОЗП (ГБ)')),
                ('is_active', models.BooleanField(default=True, help_text='Використовувати для автоматичного підбору')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_specs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_credits', models.IntegerField(default=0, verbose_name='Баланс AI-аналізів')),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
