# Generated by Django 6.0.2 on 2026-02-24 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='build',
            name='min_ram_required',
        ),
        migrations.RemoveField(
            model_name='build',
            name='performance_score',
        ),
        migrations.RemoveField(
            model_name='build',
            name='trackers',
        ),
        migrations.RemoveField(
            model_name='component',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='component',
            name='fps_impact',
        ),
        migrations.AddField(
            model_name='build',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_builds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='build',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='build',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='build',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube посилання', null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='complexity_level',
            field=models.CharField(choices=[('low', 'Низька'), ('med', 'Середня'), ('high', 'Висока')], default='low', help_text='Навантаження на систему', max_length=10),
        ),
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, help_text='Технічні деталі для ШІ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Про себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Користувач'), ('manager', 'Менеджер контенту'), ('admin', 'Адміністратор')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='build',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='builds', to='builds.component'),
        ),
        migrations.AlterField(
            model_name='build',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='tags',
            field=models.CharField(help_text='Low-PC, Winter, Realistic', max_length=255),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('script', 'Скрипт'), ('texture', 'Текстура'), ('audio', 'Аудіо'), ('graphic', 'Графіка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pcspecs',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Використовувати для автоматичного аналізу'),
        ),
        migrations.AlterField(
            model_name='pcspecs',
            name='label',
            field=models.CharField(default='Мій ПК', help_text='Напр: Домашній ПК', max_length=100),
        ),
        migrations.AlterField(
            model_name='pcspecs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_specs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='ai_credits',
            field=models.IntegerField(default=5, verbose_name='Баланс AI-аналізів'),
        ),
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.TextField()),
                ('predicted_fps', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.build')),
                ('specs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builds.pcspecs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuildImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='build_gallery/')),
                ('is_cover', models.BooleanField(default=False)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='builds.build')),
            ],
        ),
    ]
