# Generated by Django 6.0.2 on 2026-02-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_remove_build_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysislog',
            name='predicted_fps',
            field=models.CharField(max_length=255),
        ),
    ]
