# Generated by Django 6.0.2 on 2026-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_alter_aianalysislog_predicted_fps'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
