# Generated by Django 6.0.2 on 2026-03-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_alter_build_info_hash_alter_build_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='build_type',
            field=models.CharField(choices=[('build', 'Збірка'), ('script', 'Скрипт'), ('mix', 'Мікс')], default='build', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='build',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Рейтинг (1–5)'),
        ),
        migrations.AlterField(
            model_name='build',
            name='tags',
            field=models.CharField(blank=True, help_text='Через кому: Low-PC, Winter, Realistic', max_length=255),
        ),
        migrations.AlterField(
            model_name='build',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='complexity_level',
            field=models.CharField(choices=[('low', 'Низька'), ('med', 'Середня'), ('high', 'Висока')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pcspecs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pcspecs',
            name='label',
            field=models.CharField(default='Мій ПК', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='builds.build')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'build')},
            },
        ),
    ]
