# Generated by Django 6.0.2 on 2026-03-04 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_supportticket_ticketreply_ticketscreenshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aianalysislog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='aianalysislog',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aianalysislog',
            name='risks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_type',
            field=models.CharField(choices=[('build', 'Збірка'), ('script', 'Скрипт')], default='build', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='builds.supportticket'),
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'Виконується'), ('done', 'Готово'), ('error', 'Помилка')], default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to='builds.build')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aianalysislog',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='builds.analysistask'),
        ),
        migrations.CreateModel(
            name='BuildSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('build_type', models.CharField(choices=[('build', 'Збірка'), ('script', 'Скрипт')], default='build', max_length=10, verbose_name='Тип')),
                ('tags', models.CharField(blank=True, help_text='Через кому: Low-PC, Winter', max_length=255)),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='YouTube посилання')),
                ('source_file', models.FileField(upload_to='submission_archives/', verbose_name='Архів збірки')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='submission_covers/', verbose_name='Обкладинка')),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=10, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина відхилення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_build', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_submission', to='builds.build')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Перевірив')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на публікацію',
                'verbose_name_plural': 'Заявки на публікацію',
                'ordering': ['-created_at'],
            },
        ),
    ]
