# Generated by Django 6.0.2 on 2026-03-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_buildpostreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='archive_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='archive_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
