# Generated by Django 6.0.2 on 2026-03-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0011_build_archive_identifier_build_archive_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketreply",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="support_reply_images/"
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
