# Generated by Django 6.0.2 on 2026-04-15 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0012_ticketreply_image_alter_ticketreply_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("post_reply", "Відповідь на пост"),
                            ("ticket_reply", "Відповідь у зверненні"),
                            ("ai_done", "Результат AI-аналізу"),
                            ("moderation_warning", "Попередження модерації"),
                            ("submission_status", "Зміна статусу заявки"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("actor_name", models.CharField(blank=True, max_length=150)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("link_type", models.CharField(blank=True, max_length=50)),
                ("link_params", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сповіщення",
                "verbose_name_plural": "Сповіщення",
                "ordering": ["-created_at"],
            },
        ),
    ]
