# Generated by Django 6.0.2 on 2026-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0014_appealchat_appealmessage_userblock_appealchat_block_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcspecs",
            name="pc_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Назва ПК"),
        ),
        migrations.AddField(
            model_name="pcspecs",
            name="ram_mhz",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Швидкість ОЗП (МГц)"
            ),
        ),
    ]
