# Generated by Django 6.0.2 on 2026-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0015_pcspecs_pc_name_pcspecs_ram_mhz"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="download_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Завантажень"),
        ),
    ]
