# Generated by Django 6.0.2 on 2026-04-19 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0017_profile_banner_profile_last_seen_profilemessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="is_premium_only",
            field=models.BooleanField(default=False, verbose_name="Тільки для преміум"),
        ),
        migrations.CreateModel(
            name="FeaturedBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Дійсно до")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured",
                        to="builds.build",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_builds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Просування збірки",
                "verbose_name_plural": "Просування збірок",
            },
        ),
    ]
