# Generated by Django 6.0.2 on 2026-04-22 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0019_workshopdraft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_premium",
        ),
        migrations.AddField(
            model_name="profile",
            name="av_checks_left",
            field=models.IntegerField(
                default=0, verbose_name="Залишилось антивірусних перевірок"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_frame",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Без рамки"),
                    ("gold", "Золота"),
                    ("animated", "Анімована"),
                    ("neon", "Неонова"),
                ],
                default="",
                max_length=20,
                verbose_name="Рамка аватарки (Pro)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Безкоштовно"),
                    ("standard", "Стандарт $6/міс"),
                    ("pro", "Pro $17/міс"),
                ],
                default="free",
                max_length=10,
                verbose_name="План підписки",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_color",
            field=models.CharField(
                blank=True, default="", max_length=7, verbose_name="Колір ніку (Pro)"
            ),
        ),
        migrations.CreateModel(
            name="VirusScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("clean", "Чисто"),
                            ("suspicious", "Підозріло"),
                            ("dangerous", "Небезпечно"),
                        ],
                        max_length=10,
                    ),
                ),
                ("engines_total", models.IntegerField(default=0)),
                ("engines_detected", models.IntegerField(default=0)),
                ("scan_id", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virus_scan",
                        to="builds.build",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="virus_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат антивірусної перевірки",
            },
        ),
        migrations.CreateModel(
            name="UserScanPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_purchases",
                        to="builds.build",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "build")},
            },
        ),
    ]
