# Generated by Django 6.0.2 on 2026-04-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0020_remove_profile_is_premium_profile_av_checks_left_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="plan_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Підписка діє до"
            ),
        ),
    ]
