# Generated by Django 6.0.2 on 2026-05-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0021_profile_plan_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildsubmission",
            name="archive_identifier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Archive.org ID"
            ),
        ),
        migrations.AddField(
            model_name="buildsubmission",
            name="archive_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Archive.org URL"
            ),
        ),
        migrations.AddField(
            model_name="buildsubmission",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує завантаження"),
                    ("uploading", "Завантажується"),
                    ("done", "Завантажено"),
                    ("failed", "Помилка"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус завантаження",
            ),
        ),
        migrations.AlterField(
            model_name="buildsubmission",
            name="source_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="submission_archives/",
                verbose_name="Архів збірки",
            ),
        ),
    ]
