# Generated by Django 6.0.2 on 2026-05-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0022_buildsubmission_archive_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildsubmission",
            name="upload_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Час завершення завантаження"
            ),
        ),
    ]
